"""
Remove model name prefix from all fields.

Renames fields like user_code -> code, collection_headline -> headline, etc.
Django's RenameField automatically updates FK to_field references.
"""

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_add_order_fields"),
    ]

    operations = [
        # === Theeeme (rename PK first - Collection FK references it) ===
        migrations.RenameField(
            model_name="theeeme",
            old_name="theeeme_code",
            new_name="code",
        ),
        migrations.RenameField(
            model_name="theeeme",
            old_name="theeeme_name",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="theeeme",
            old_name="theeeme_01",
            new_name="color_01",
        ),
        migrations.RenameField(
            model_name="theeeme",
            old_name="theeeme_02",
            new_name="color_02",
        ),
        migrations.RenameField(
            model_name="theeeme",
            old_name="theeeme_03",
            new_name="color_03",
        ),
        migrations.RenameField(
            model_name="theeeme",
            old_name="theeeme_04",
            new_name="color_04",
        ),
        migrations.RenameField(
            model_name="theeeme",
            old_name="theeeme_05",
            new_name="color_05",
        ),
        migrations.RenameField(
            model_name="theeeme",
            old_name="theeeme_06",
            new_name="color_06",
        ),
        # === User (rename PK first) ===
        migrations.RenameField(
            model_name="user",
            old_name="user_code",
            new_name="code",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="user_email",
            new_name="email",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="user_name",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="user_created",
            new_name="created",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="user_last_activity",
            new_name="last_activity",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="user_own_collections",
            new_name="own_collections",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="user_invited_collections",
            new_name="invited_collections",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="user_things",
            new_name="things",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="user_headline",
            new_name="headline",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="user_thumbnail",
            new_name="thumbnail",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="user_hero",
            new_name="hero",
        ),
        # === Collection (PK and fields, including FK rename) ===
        migrations.RenameField(
            model_name="collection",
            old_name="collection_code",
            new_name="code",
        ),
        migrations.RenameField(
            model_name="collection",
            old_name="collection_owner",
            new_name="owner",
        ),
        migrations.RenameField(
            model_name="collection",
            old_name="collection_created",
            new_name="created",
        ),
        migrations.RenameField(
            model_name="collection",
            old_name="collection_headline",
            new_name="headline",
        ),
        migrations.RenameField(
            model_name="collection",
            old_name="collection_description",
            new_name="description",
        ),
        migrations.RenameField(
            model_name="collection",
            old_name="collection_thumbnail",
            new_name="thumbnail",
        ),
        migrations.RenameField(
            model_name="collection",
            old_name="collection_hero",
            new_name="hero",
        ),
        migrations.RenameField(
            model_name="collection",
            old_name="collection_status",
            new_name="status",
        ),
        migrations.RenameField(
            model_name="collection",
            old_name="collection_things",
            new_name="things",
        ),
        migrations.RenameField(
            model_name="collection",
            old_name="collection_invites",
            new_name="invites",
        ),
        migrations.RenameField(
            model_name="collection",
            old_name="collection_theeeme",
            new_name="theeeme",
        ),
        # === Thing (PK and fields) ===
        migrations.RenameField(
            model_name="thing",
            old_name="thing_code",
            new_name="code",
        ),
        migrations.RenameField(
            model_name="thing",
            old_name="thing_type",
            new_name="type",
        ),
        migrations.RenameField(
            model_name="thing",
            old_name="thing_owner",
            new_name="owner",
        ),
        migrations.RenameField(
            model_name="thing",
            old_name="thing_created",
            new_name="created",
        ),
        migrations.RenameField(
            model_name="thing",
            old_name="thing_headline",
            new_name="headline",
        ),
        migrations.RenameField(
            model_name="thing",
            old_name="thing_description",
            new_name="description",
        ),
        migrations.RenameField(
            model_name="thing",
            old_name="thing_thumbnail",
            new_name="thumbnail",
        ),
        migrations.RenameField(
            model_name="thing",
            old_name="thing_pictures",
            new_name="pictures",
        ),
        migrations.RenameField(
            model_name="thing",
            old_name="thing_status",
            new_name="status",
        ),
        migrations.RenameField(
            model_name="thing",
            old_name="thing_faq",
            new_name="faqs",
        ),
        migrations.RenameField(
            model_name="thing",
            old_name="thing_fee",
            new_name="fee",
        ),
        migrations.RenameField(
            model_name="thing",
            old_name="thing_deal",
            new_name="deal",
        ),
        migrations.RenameField(
            model_name="thing",
            old_name="thing_available",
            new_name="available",
        ),
        # === FAQ ===
        migrations.RenameField(
            model_name="faq",
            old_name="faq_code",
            new_name="code",
        ),
        migrations.RenameField(
            model_name="faq",
            old_name="faq_thing",
            new_name="thing",
        ),
        migrations.RenameField(
            model_name="faq",
            old_name="faq_created",
            new_name="created",
        ),
        migrations.RenameField(
            model_name="faq",
            old_name="faq_questioner",
            new_name="questioner",
        ),
        migrations.RenameField(
            model_name="faq",
            old_name="faq_question",
            new_name="question",
        ),
        migrations.RenameField(
            model_name="faq",
            old_name="faq_answer",
            new_name="answer",
        ),
        migrations.RenameField(
            model_name="faq",
            old_name="faq_is_visible",
            new_name="is_visible",
        ),
        # === RSVP (only rsvp_ prefixed fields, keep cross-model refs) ===
        migrations.RenameField(
            model_name="rsvp",
            old_name="rsvp_code",
            new_name="code",
        ),
        migrations.RenameField(
            model_name="rsvp",
            old_name="rsvp_created",
            new_name="created",
        ),
        migrations.RenameField(
            model_name="rsvp",
            old_name="rsvp_action",
            new_name="action",
        ),
        migrations.RenameField(
            model_name="rsvp",
            old_name="rsvp_target_code",
            new_name="target_code",
        ),
        migrations.RenameField(
            model_name="rsvp",
            old_name="rsvp_context",
            new_name="context",
        ),
        # === BookingPeriod (only booking_ prefixed fields, keep cross-model refs) ===
        migrations.RenameField(
            model_name="bookingperiod",
            old_name="booking_code",
            new_name="code",
        ),
        migrations.RenameField(
            model_name="bookingperiod",
            old_name="booking_created",
            new_name="created",
        ),
    ]
