# Generated by Django 5.2.10 on 2026-02-09 12:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_rename_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thing',
            name='faqs',
        ),
        migrations.RemoveField(
            model_name='user',
            name='invited_collections',
        ),
        migrations.RemoveField(
            model_name='user',
            name='own_collections',
        ),
        migrations.RemoveField(
            model_name='user',
            name='things',
        ),
        migrations.AlterField(
            model_name='bookingperiod',
            name='owner_code',
            field=models.ForeignKey(db_column='owner_code', on_delete=django.db.models.deletion.CASCADE, related_name='booking_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bookingperiod',
            name='requester_code',
            field=models.ForeignKey(db_column='requester_code', on_delete=django.db.models.deletion.CASCADE, related_name='booking_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bookingperiod',
            name='thing_code',
            field=models.ForeignKey(db_column='thing_code', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='core.thing'),
        ),
        migrations.RemoveField(
            model_name='collection',
            name='invites',
        ),
        migrations.AlterField(
            model_name='collection',
            name='owner',
            field=models.ForeignKey(db_column='owner', on_delete=django.db.models.deletion.CASCADE, related_name='owned_collections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='collection',
            name='things',
        ),
        migrations.AlterField(
            model_name='faq',
            name='questioner',
            field=models.ForeignKey(db_column='questioner', on_delete=django.db.models.deletion.CASCADE, related_name='asked_faqs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='faq',
            name='thing',
            field=models.ForeignKey(db_column='thing', on_delete=django.db.models.deletion.CASCADE, related_name='faq_set', to='core.thing'),
        ),
        migrations.AlterField(
            model_name='rsvp',
            name='user_code',
            field=models.ForeignKey(db_column='user_code', on_delete=django.db.models.deletion.CASCADE, related_name='rsvps', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='thing',
            name='deal',
        ),
        migrations.AlterField(
            model_name='thing',
            name='owner',
            field=models.ForeignKey(db_column='owner', on_delete=django.db.models.deletion.CASCADE, related_name='owned_things', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='collection',
            name='invites',
            field=models.ManyToManyField(blank=True, db_table='collection_invites', related_name='invited_to_collections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='collection',
            name='things',
            field=models.ManyToManyField(blank=True, db_table='collection_things', related_name='collections', to='core.thing'),
        ),
        migrations.AddField(
            model_name='thing',
            name='deal',
            field=models.ManyToManyField(blank=True, db_table='thing_deals', related_name='deals', to=settings.AUTH_USER_MODEL),
        ),
    ]
