# Generated by Django 5.2.10 on 2026-02-09 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_remove_thing_faqs_remove_user_invited_collections_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rsvp",
            name="collection_code",
        ),
    ]
