# Generated by Django 5.2.10 on 2026-02-26 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_move_theeeme_to_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingperiod',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired')], db_index=True, default='PENDING', max_length=8),
        ),
        migrations.AlterField(
            model_name='rsvp',
            name='action',
            field=models.CharField(choices=[('MAGIC_LINK', 'Magic Link'), ('COLLECTION_INVITE', 'Collection Invite'), ('COLLECTION_REJECT', 'Collection Reject'), ('BOOKING_ACCEPT', 'Booking Accept'), ('BOOKING_REJECT', 'Booking Reject')], db_index=True, default='MAGIC_LINK', max_length=20),
        ),
        migrations.AlterField(
            model_name='rsvp',
            name='target_code',
            field=models.CharField(blank=True, db_index=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='theeeme',
            field=models.ForeignKey(db_column='user_theeeme', default='HDS000', on_delete=django.db.models.deletion.PROTECT, related_name='users', to='core.theeeme'),
        ),
    ]
