# Generated by Django 5.2.10 on 2026-02-26 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_add_indexes_booking_status_rsvp_action_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingperiod',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], db_index=True, default='PENDING', max_length=9),
        ),
    ]
