# Generated by Django 5.2.12 on 2026-03-23 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_booking_status_cancelled'),
    ]

    operations = [
        migrations.AddField(
            model_name='thing',
            name='availability',
            field=models.CharField(blank=True, choices=[('IMMEDIATE', 'Immediate'), ('NEXT_WEEK', 'Next week'), ('END_OF_MONTH', 'End of month'), ('NEXT_MONTH', 'Next month')], default='', max_length=12),
        ),
        migrations.AddField(
            model_name='thing',
            name='condition',
            field=models.CharField(blank=True, choices=[('NEW', 'New'), ('GOOD', 'Good condition'), ('FAIR', 'Fair'), ('USED', 'Used'), ('WELL_USED', 'Well used'), ('ALMOST_JUNK', 'Almost junk')], default='', max_length=12),
        ),
        migrations.AddField(
            model_name='thing',
            name='location',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
