# Generated by Django 5.2.12 on 2026-03-24 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_thing_availability_location_condition"),
    ]

    operations = [
        migrations.AlterField(
            model_name="theeeme",
            name="color_01",
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name="theeeme",
            name="color_02",
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name="theeeme",
            name="color_03",
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name="theeeme",
            name="color_04",
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name="theeeme",
            name="color_05",
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name="theeeme",
            name="color_06",
            field=models.CharField(max_length=32),
        ),
    ]
