# Generated by Django 5.2.12 on 2026-03-24 11:50

import django.db.models.deletion
from django.db import migrations, models


def migrate_hds000_to_bussi(apps, schema_editor):
    """Move users on old default HDS000 to new default Bussi."""
    User = apps.get_model("core", "User")
    User.objects.filter(theeeme="HDS000").update(theeeme="Bussi")


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_theeeme_color_fields_to_hds_names"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="theeeme",
            field=models.ForeignKey(
                db_column="user_theeeme",
                default="Bussi",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="users",
                to="core.theeeme",
            ),
        ),
        migrations.RunPython(migrate_hds000_to_bussi, migrations.RunPython.noop),
    ]
