# Generated by Django 5.2.12 on 2026-03-24 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0025_default_theeeme_to_bussi"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="theeeme",
            name="color_06",
        ),
        migrations.RemoveField(
            model_name="theeeme",
            name="name",
        ),
    ]
