# Generated by Django 5.2.12 on 2026-03-24 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0026_remove_theeeme_name_and_color_06"),
    ]

    operations = [
        migrations.AddField(
            model_name="theeeme",
            name="name",
            field=models.CharField(default="", max_length=16),
        ),
    ]
