# Generated by Django 5.2.12 on 2026-03-24 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0028_populate_theeeme_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="theeeme",
            field=models.ForeignKey(
                db_column="user_theeeme",
                default="BU331",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="users",
                to="core.theeeme",
            ),
        ),
    ]
