# Generated by Django 5.2.12 on 2026-03-24 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0029_default_theeeme_bu331"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="theeeme",
            field=models.ForeignKey(
                db_column="user_theeeme",
                default="BUU331",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="users",
                to="core.theeeme",
            ),
        ),
    ]
