# Generated by Django 5.2.12 on 2026-03-25 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0030_default_theeeme_buu331"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="koro",
            field=models.CharField(
                choices=[
                    ("basic", "Basic"),
                    ("beat", "Beat"),
                    ("calm", "Calm"),
                    ("pulse", "Pulse"),
                    ("storm", "Storm"),
                    ("wave", "Wave"),
                ],
                default="basic",
                max_length=5,
            ),
        ),
    ]
