# Generated by Django 5.2.12 on 2026-03-25 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0031_add_koro_to_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="koro",
            field=models.CharField(
                choices=[
                    ("basic", "Basic"),
                    ("beat", "Beat"),
                    ("calm", "Calm"),
                    ("pulse", "Pulse"),
                    ("vibration", "Vibration"),
                    ("wave", "Wave"),
                ],
                default="basic",
                max_length=9,
            ),
        ),
    ]
