# Generated by Django 5.2.12 on 2026-03-30 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0033_remove_available_from_thing"),
    ]

    operations = [
        migrations.AddField(
            model_name="theeeme",
            name="color_06",
            field=models.CharField(default="", max_length=32),
        ),
    ]
