# Generated by Django 5.2.12 on 2026-03-30 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0034_add_color_06_to_theeeme"),
    ]

    operations = [
        migrations.AlterField(
            model_name="theeeme",
            name="color_06",
            field=models.CharField(max_length=32),
        ),
    ]
