# Generated by Django 5.2.12 on 2026-04-01 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0041_seed_demo_faqs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collection",
            name="hero",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="collection",
            name="thumbnail",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="thing",
            name="thumbnail",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="user",
            name="hero",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="user",
            name="thumbnail",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
