# Generated by Django 5.2.12 on 2026-04-01 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0042_expand_image_fields_for_cloudinary_public_ids"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="thing",
            name="pictures",
        ),
    ]
