# Generated by Django 5.2.12 on 2026-04-01 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0043_remove_pictures_from_thing"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="collection",
            name="hero",
        ),
    ]
