# Generated by Django 5.2.12 on 2026-04-01 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0044_remove_hero_from_collection"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="hero",
        ),
    ]
