# Generated by Django 5.2.12 on 2026-04-09 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0045_remove_hero_from_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="collection",
            name="thumbnail",
        ),
        migrations.RemoveField(
            model_name="user",
            name="thumbnail",
        ),
    ]
