# Generated by Django 5.2.12 on 2026-04-10 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0048_seed_demo_collections_lili_lolo_lulu"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="is_onboarding",
            field=models.BooleanField(default=False),
        ),
    ]
