# Generated by Django 5.2.12 on 2026-04-17 14:41

import core.utils
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0051_seed_demo_things_lili_lolo_lulu"),
    ]

    operations = [
        migrations.CreateModel(
            name="ThingTransfer",
            fields=[
                (
                    "code",
                    models.CharField(
                        default=core.utils.generate_id,
                        max_length=6,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("lent_date", models.DateField()),
                ("returned_date", models.DateField(blank=True, null=True)),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "booking",
                    models.ForeignKey(
                        blank=True,
                        db_column="booking",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transfer",
                        to="core.bookingperiod",
                    ),
                ),
                (
                    "from_user",
                    models.ForeignKey(
                        db_column="from_user",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transfers_out",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "thing",
                    models.ForeignKey(
                        db_column="thing",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transfers",
                        to="core.thing",
                    ),
                ),
                (
                    "to_user",
                    models.ForeignKey(
                        db_column="to_user",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transfers_in",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "thing_transfers",
                "ordering": ["-lent_date"],
            },
        ),
    ]
