# Generated by Django 5.2.12 on 2026-04-17 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0052_create_thingtransfer"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="mode",
            field=models.CharField(
                choices=[("PROPRIETARY", "Proprietary"), ("COMMUNITY", "Community")],
                default="PROPRIETARY",
                max_length=12,
            ),
        ),
    ]
