# Generated by Django 5.2.12 on 2026-04-17 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0053_add_collection_mode"),
    ]

    operations = [
        migrations.AddField(
            model_name="thing",
            name="event_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="thing",
            name="type",
            field=models.CharField(
                choices=[
                    ("GIFT_THING", "Gift Thing"),
                    ("SELL_THING", "Sell Thing"),
                    ("ORDER_THING", "Order Thing"),
                    ("RENT_THING", "Rent Thing"),
                    ("LEND_THING", "Lend Thing"),
                    ("SHARE_THING", "Share Thing"),
                    ("EVENT_THING", "Event Thing"),
                ],
                default="GIFT_THING",
                max_length=16,
            ),
        ),
    ]
