# Generated by Django 5.2.12 on 2026-04-18 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0054_add_event_thing"),
    ]

    operations = [
        migrations.AlterField(
            model_name="thing",
            name="type",
            field=models.CharField(
                choices=[
                    ("GIFT_THING", "Gift Thing"),
                    ("SELL_THING", "Sell Thing"),
                    ("ORDER_THING", "Order Thing"),
                    ("RENT_THING", "Rent Thing"),
                    ("LEND_THING", "Lend Thing"),
                    ("SHARE_THING", "Share Thing"),
                    ("EVENT_THING", "Event Thing"),
                    ("WISH_THING", "Wish Thing"),
                ],
                default="GIFT_THING",
                max_length=16,
            ),
        ),
    ]
