# Generated by Django 5.2.12 on 2026-04-18 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0055_add_wish_thing"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="digest_frequency",
            field=models.CharField(
                choices=[("NONE", "None"), ("WEEKLY", "Weekly"), ("MONTHLY", "Monthly")],
                default="NONE",
                max_length=7,
            ),
        ),
    ]
