# Generated by Django 5.2.12 on 2026-04-18 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0056_add_digest_frequency"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookingperiod",
            name="end_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bookingperiod",
            name="start_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="thing",
            name="booking_unit",
            field=models.CharField(
                blank=True, choices=[("DAY", "Day"), ("HOUR", "Hour")], default="", max_length=4
            ),
        ),
        migrations.AlterField(
            model_name="thing",
            name="type",
            field=models.CharField(
                choices=[
                    ("GIFT_THING", "Gift Thing"),
                    ("SELL_THING", "Sell Thing"),
                    ("ORDER_THING", "Order Thing"),
                    ("RENT_THING", "Rent Thing"),
                    ("LEND_THING", "Lend Thing"),
                    ("SHARE_THING", "Share Thing"),
                    ("EVENT_THING", "Event Thing"),
                    ("WISH_THING", "Wish Thing"),
                    ("ASSET_THING", "Asset Thing"),
                ],
                default="GIFT_THING",
                max_length=16,
            ),
        ),
    ]
