# Generated by Django 5.2.12 on 2026-04-19 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0057_add_asset_thing"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookingperiod",
            name="offered_things",
            field=models.ManyToManyField(
                blank=True,
                db_table="booking_offered_things",
                related_name="swap_offers",
                to="core.thing",
            ),
        ),
        migrations.AddField(
            model_name="collection",
            name="is_swap",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="thing",
            name="type",
            field=models.CharField(
                choices=[
                    ("GIFT_THING", "Gift Thing"),
                    ("SELL_THING", "Sell Thing"),
                    ("ORDER_THING", "Order Thing"),
                    ("RENT_THING", "Rent Thing"),
                    ("LEND_THING", "Lend Thing"),
                    ("SHARE_THING", "Share Thing"),
                    ("EVENT_THING", "Event Thing"),
                    ("WISH_THING", "Wish Thing"),
                    ("ASSET_THING", "Asset Thing"),
                    ("SWAP_THING", "Swap Thing"),
                ],
                default="GIFT_THING",
                max_length=16,
            ),
        ),
    ]
