# Generated by Django 5.2.12 on 2026-04-19 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0058_add_swap_thing"),
    ]

    operations = [
        migrations.AddField(
            model_name="thing",
            name="availability_schedule",
            field=models.JSONField(
                blank=True,
                default=None,
                help_text="Recurring availability windows: [{days: [1-7], start_time, end_time}]",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="thing",
            name="slot_duration",
            field=models.PositiveIntegerField(
                blank=True, help_text="Slot duration in minutes (15, 30, or 60)", null=True
            ),
        ),
        migrations.AlterField(
            model_name="bookingperiod",
            name="thing_type",
            field=models.CharField(default="GIFT_THING", max_length=17),
        ),
        migrations.AlterField(
            model_name="thing",
            name="type",
            field=models.CharField(
                choices=[
                    ("GIFT_THING", "Gift Thing"),
                    ("SELL_THING", "Sell Thing"),
                    ("ORDER_THING", "Order Thing"),
                    ("RENT_THING", "Rent Thing"),
                    ("LEND_THING", "Lend Thing"),
                    ("SHARE_THING", "Share Thing"),
                    ("EVENT_THING", "Event Thing"),
                    ("WISH_THING", "Wish Thing"),
                    ("ASSET_THING", "Asset Thing"),
                    ("SWAP_THING", "Swap Thing"),
                    ("APPOINTMENT_THING", "Appointment Thing"),
                ],
                default="GIFT_THING",
                max_length=17,
            ),
        ),
    ]
