# Generated by Django 5.2.12 on 2026-04-20 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0059_add_appointment_thing"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="is_share",
            field=models.BooleanField(default=False),
        ),
    ]
