# Generated by Django 5.2.12 on 2026-04-20 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0060_add_is_share_to_collection"),
    ]

    operations = [
        migrations.AddField(
            model_name="thing",
            name="documents",
            field=models.JSONField(
                blank=True,
                default=None,
                help_text="Attached documents: [{public_id, filename, content_type}]. Max 5.",
                null=True,
            ),
        ),
    ]
