# Generated by Django 5.2.12 on 2026-04-22 09:17

import core.models.user
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0073_lili_circuit_swap_onboarding"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="theeeme",
            field=models.ForeignKey(
                db_column="user_theeeme",
                default=core.models.user._random_theeeme,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="users",
                to="core.theeeme",
            ),
        ),
    ]
