# Generated by Django 5.2.12 on 2026-04-22 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0074_random_theeeme_default"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="thumbnail",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
