# Generated by Django 5.2.12 on 2026-04-24 09:22

import core.models.notification
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0077_add_notification_prefs_to_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="InAppNotification",
            fields=[
                (
                    "code",
                    models.CharField(
                        default=core.models.notification._generate_code,
                        max_length=6,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("type", models.CharField(max_length=32)),
                ("payload", models.JSONField(default=dict)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inbox_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "in_app_notifications",
                "ordering": ["-created"],
            },
        ),
    ]
