# Generated by Django 5.2.12 on 2026-05-03 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0089_remove_user_analytics_opt_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='allowed_thing_types',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
