# Generated by Django 5.2.12 on 2026-05-31 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0090_collection_allowed_thing_types'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='thingtransfer',
            constraint=models.UniqueConstraint(fields=('booking', 'thing'), name='uniq_transfer_per_booking_thing'),
        ),
    ]
