# Generated by Django 5.2.15 on 2026-06-12 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0094_remove_asset_thing'),
    ]

    operations = [
        migrations.AddField(
            model_name='thing',
            name='gallery',
            field=models.JSONField(blank=True, default=list, help_text='Additional photos beyond the cover thumbnail: an ordered list of Cloudinary public_ids. Max 8. Things only (not collections).'),
        ),
        migrations.AddField(
            model_name='user',
            name='about',
            field=models.CharField(blank=True, default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
