# Generated by Django 5.2.15 on 2026-06-12 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0095_thing_gallery_user_about_user_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text='Owner-defined tag vocabulary for this collection: an ordered list of free-text labels. Things in the collection may be tagged with a subset. Max 12.'),
        ),
        migrations.AddField(
            model_name='thing',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text="Owner-defined tags assigned to this thing — a subset of its collection's tag vocabulary (Collection.tags). Max 12."),
        ),
    ]
