# Generated by Django 5.2.15 on 2026-06-12 14:34

import core.utils
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0096_collection_tags_thing_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='WishResponse',
            fields=[
                ('code', models.CharField(default=core.utils.generate_id, max_length=6, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('kind', models.CharField(choices=[('HAVE_THIS', 'Have this'), ('KNOW_WHERE', 'Know where'), ('CAN_MAKE', 'Can make it')], max_length=10)),
                ('message', models.CharField(blank=True, default='', max_length=256)),
                ('url', models.CharField(blank=True, default='', max_length=255)),
                ('fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted')], default='PENDING', max_length=8)),
                ('responder', models.ForeignKey(db_column='responder', on_delete=django.db.models.deletion.CASCADE, related_name='wish_responses', to=settings.AUTH_USER_MODEL)),
                ('thing', models.ForeignKey(blank=True, db_column='offered_thing', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offered_in_responses', to='core.thing')),
                ('wish', models.ForeignKey(db_column='wish', on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='core.thing')),
            ],
            options={
                'db_table': 'wish_responses',
                'ordering': ['-created'],
            },
        ),
    ]
