# Generated by Django 5.2.15 on 2026-06-18 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0100_rsvp_token"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="prefs_token",
        ),
    ]
