# Generated by Django 5.2.15 on 2026-06-18 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0101_remove_user_prefs_token'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='bookingperiod',
            index=models.Index(fields=['thing_code', 'status'], name='booking_thing_status_idx'),
        ),
        migrations.AddIndex(
            model_name='thingtransfer',
            index=models.Index(fields=['thing', 'lent_date'], name='transfer_thing_lentdate_idx'),
        ),
    ]
