# Generated by Django 5.2.15 on 2026-06-19 09:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0102_bookingperiod_booking_thing_status_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="age_range",
            field=models.CharField(
                blank=True,
                choices=[
                    ("UP_TO_21", "21 or under"),
                    ("22_35", "22-35"),
                    ("36_55", "36-55"),
                    ("56_PLUS", "56 or over"),
                ],
                default="",
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="postal_code",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
    ]
