# Generated by Django 5.2.15 on 2026-06-28 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0104_collection_visibility'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingperiod',
            name='delivery_date',
        ),
        migrations.RemoveField(
            model_name='bookingperiod',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='thing',
            name='type',
            field=models.CharField(choices=[('GIFT_THING', 'Gift Thing'), ('SELL_THING', 'Sell Thing'), ('RENT_THING', 'Rent Thing'), ('LEND_THING', 'Lend Thing'), ('SHARE_THING', 'Share Thing'), ('WISH_THING', 'Wish Thing'), ('SWAP_THING', 'Swap Thing')], default='GIFT_THING', max_length=11),
        ),
    ]
