# Generated by Django 5.2.15 on 2026-06-30 12:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0105_remove_bookingperiod_delivery_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="collection",
            name="is_minimalist",
        ),
        migrations.RemoveField(
            model_name="thing",
            name="documents",
        ),
    ]
