# Generated by Django 5.2.15 on 2026-07-02 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0106_remove_collection_is_minimalist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inappnotification',
            name='type',
            field=models.CharField(choices=[('BROADCAST', 'Broadcast'), ('COLLECTION_DELETED', 'Collection Deleted'), ('COLLECTION_REVOKED', 'Collection Revoked'), ('BOOKING_ACCEPTED', 'Booking Accepted'), ('BOOKING_REJECTED', 'Booking Rejected'), ('BOOKING_REQUESTED', 'Booking Requested'), ('BOOKING_UNAVAILABLE', 'Booking Unavailable'), ('SWAP_REQUESTED', 'Swap Requested'), ('FAQ_QUESTION', 'Faq Question'), ('FAQ_ANSWERED', 'Faq Answered'), ('FAQ_HIDDEN', 'Faq Hidden'), ('INVITE_REJECTED', 'Invite Rejected'), ('MEMBER_LEFT', 'Member Left'), ('WISH_POSTED', 'Wish Posted'), ('WISH_RESPONSE', 'Wish Response'), ('WISH_ACCEPTED', 'Wish Accepted')], max_length=32),
        ),
    ]
