# Generated by Django 5.2.15 on 2026-07-03 06:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import core.utils


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0107_alter_inappnotification_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inappnotification",
            name="type",
            field=models.CharField(
                choices=[
                    ("BROADCAST", "Broadcast"),
                    ("COLLECTION_DELETED", "Collection Deleted"),
                    ("COLLECTION_REVOKED", "Collection Revoked"),
                    ("BOOKING_ACCEPTED", "Booking Accepted"),
                    ("BOOKING_REJECTED", "Booking Rejected"),
                    ("BOOKING_REQUESTED", "Booking Requested"),
                    ("BOOKING_UNAVAILABLE", "Booking Unavailable"),
                    ("SWAP_REQUESTED", "Swap Requested"),
                    ("FAQ_QUESTION", "Faq Question"),
                    ("FAQ_ANSWERED", "Faq Answered"),
                    ("FAQ_HIDDEN", "Faq Hidden"),
                    ("INVITE_REJECTED", "Invite Rejected"),
                    ("MEMBER_LEFT", "Member Left"),
                    ("THING_REPORTED", "Thing Reported"),
                    ("WISH_POSTED", "Wish Posted"),
                    ("WISH_RESPONSE", "Wish Response"),
                    ("WISH_ACCEPTED", "Wish Accepted"),
                ],
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "code",
                    models.CharField(
                        default=core.utils.generate_id,
                        max_length=6,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("thing_headline", models.CharField(blank=True, max_length=64)),
                ("created", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                (
                    "reporter",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reports_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "thing",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reports",
                        to="core.thing",
                    ),
                ),
            ],
            options={
                "db_table": "reports",
                "ordering": ["-created"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("thing", "reporter"), name="unique_report_per_reporter_thing"
                    )
                ],
            },
        ),
    ]
