# Generated by Django 5.2.15 on 2026-07-03 12:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0108_alter_inappnotification_type_report"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="rental_durations",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="collection",
            name="rental_weekdays",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
