# Generated by Django 5.2.15 on 2026-07-04 15:31

import core.utils
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0109_collection_rental_durations_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('code', models.CharField(default=core.utils.generate_id, max_length=6, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('USER_JOINED', 'User Joined'), ('COLLECTION_CREATED', 'Collection Created'), ('COLLECTION_DELETED', 'Collection Deleted'), ('THING_ADDED', 'Thing Added'), ('THING_REMOVED', 'Thing Removed'), ('MEMBER_JOINED', 'Member Joined'), ('MEMBER_LEFT', 'Member Left'), ('FAQ_ASKED', 'Faq Asked'), ('HOLD_REQUESTED', 'Hold Requested'), ('HOLD_ACCEPTED', 'Hold Accepted')], max_length=18)),
                ('actor_code', models.CharField(blank=True, default='', max_length=6)),
                ('collection_code', models.CharField(blank=True, default='', max_length=6)),
                ('thing_code', models.CharField(blank=True, default='', max_length=6)),
                ('thing_type', models.CharField(blank=True, default='', max_length=17)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'events',
                'ordering': ['-created'],
                'indexes': [models.Index(fields=['kind', 'created'], name='events_kind_4700a2_idx')],
            },
        ),
    ]
