# Generated by Django 5.2.15 on 2026-07-04 16:00

import core.utils
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0110_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyActivity',
            fields=[
                ('code', models.CharField(default=core.utils.generate_id, max_length=6, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_activity', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'daily_activity',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date'], name='daily_activ_date_a4c4a1_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'date'), name='unique_daily_activity_per_day')],
            },
        ),
    ]
