# Generated by Django 5.2.15 on 2026-07-11 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0112_fix_vaakuna_hero_contrast'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='notify_news',
            field=models.BooleanField(default=False),
        ),
    ]
