# Generated by Django 5.2.16 on 2026-07-11 18:35

from django.db import migrations, models


def clear_retired_age_brackets(apps, schema_editor):
    """The 2026-07 bracket expansion has no faithful mapping for the retired
    values (22_35 spans the new 22_30 AND 31_40, etc.), so they reset to
    unanswered and users re-pick from the finer scale. UP_TO_21 is unchanged
    in both scales and survives as-is."""
    User = apps.get_model("core", "User")
    User.objects.filter(age_range__in=["22_35", "36_55", "56_PLUS"]).update(age_range="")


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0113_alter_user_notify_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age_range',
            field=models.CharField(blank=True, choices=[('UP_TO_21', '21 or under'), ('22_30', '22-30'), ('31_40', '31-40'), ('41_50', '41-50'), ('51_60', '51-60'), ('61_PLUS', '61 or over')], default='', max_length=8),
        ),
        migrations.RunPython(clear_retired_age_brackets, migrations.RunPython.noop),
    ]
