# Generated by Django 5.2.16 on 2026-07-12 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0115_age_ranges_to_generations'),
    ]

    operations = [
        migrations.AddField(
            model_name='rsvp',
            name='origin',
            field=models.CharField(blank=True, choices=[('POPIN', 'Pop-in'), ('LOGIN', 'Login')], default='', max_length=5),
        ),
    ]
