# Generated by Django 5.2.16 on 2026-07-12 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0116_rsvp_origin'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='welcome_doc',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
