# Generated by Django 5.2.16 on 2026-07-12 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0117_collection_welcome_doc'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='language',
            field=models.CharField(blank=True, choices=[('es', 'Español'), ('ca', 'Català'), ('en', 'English')], default='', max_length=2),
        ),
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(blank=True, choices=[('es', 'Español'), ('ca', 'Català'), ('en', 'English')], default='', max_length=2),
        ),
    ]
