# Generated by Django 5.2.16 on 2026-07-18 12:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0119_localized_owner_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='questioner',
            field=models.ForeignKey(blank=True, db_column='questioner', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asked_faqs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rsvp',
            name='action',
            field=models.CharField(choices=[('MAGIC_LINK', 'Magic Link'), ('COLLECTION_INVITE', 'Collection Invite'), ('COLLECTION_REJECT', 'Collection Reject'), ('BOOKING_ACCEPT', 'Booking Accept'), ('BOOKING_REJECT', 'Booking Reject'), ('ACCOUNT_DELETE', 'Account Delete')], db_index=True, default='MAGIC_LINK', max_length=20),
        ),
        migrations.AlterField(
            model_name='thingtransfer',
            name='from_user',
            field=models.ForeignKey(blank=True, db_column='from_user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_out', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='thingtransfer',
            name='to_user',
            field=models.ForeignKey(blank=True, db_column='to_user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_in', to=settings.AUTH_USER_MODEL),
        ),
    ]
