"""Model factories for OIUEEI tests (``factory_boy``).

Replace the repeated ``Model.objects.create(...)`` boilerplate scattered across
the suite with declarative factories that fill in the required fields and wire
up the foreign keys. PKs (``code``) are auto-generated by each model's
``default=generate_id``, so factories never set them.

``UserFactory`` relies on ``User.theeeme`` defaulting to ``BUU331``; the autouse
``default_theeeme`` fixture in ``conftest.py`` creates that theeeme, so any test
using these factories must touch the DB (``@pytest.mark.django_db`` or a ``db``
fixture), which also brings the autouse fixture into scope.
"""

from datetime import date

import factory
from factory.django import DjangoModelFactory

from core.models import FAQ, RSVP, Collection, Thing, User
from core.models.booking import BookingPeriod
from core.models.transfer import ThingTransfer
from core.models.wish import WishResponse


class UserFactory(DjangoModelFactory):
    class Meta:
        model = User

    email = factory.Sequence(lambda n: f"user{n}@example.com")
    name = factory.Sequence(lambda n: f"User {n}")


class CollectionFactory(DjangoModelFactory):
    class Meta:
        model = Collection

    owner = factory.SubFactory(UserFactory)
    headline = factory.Sequence(lambda n: f"Collection {n}")


class ThingFactory(DjangoModelFactory):
    class Meta:
        model = Thing

    owner = factory.SubFactory(UserFactory)
    headline = factory.Sequence(lambda n: f"Thing {n}")
    type = Thing.Type.GIFT_THING


class BookingPeriodFactory(DjangoModelFactory):
    """A PENDING booking. ``thing_type``/``requester_email``/``owner_code`` are
    derived from the related thing and requester so they stay consistent by
    default; override any of them explicitly when a test needs a specific shape
    (e.g. ``start_date``/``end_date`` for date-based types)."""

    class Meta:
        model = BookingPeriod

    thing_code = factory.SubFactory(ThingFactory)
    requester_code = factory.SubFactory(UserFactory)
    thing_type = factory.LazyAttribute(lambda o: o.thing_code.type)
    requester_email = factory.LazyAttribute(lambda o: o.requester_code.email)
    owner_code = factory.LazyAttribute(lambda o: o.thing_code.owner)


class RSVPFactory(DjangoModelFactory):
    class Meta:
        model = RSVP

    user_code = factory.SubFactory(UserFactory)
    user_email = factory.LazyAttribute(lambda o: o.user_code.email)


class FAQFactory(DjangoModelFactory):
    class Meta:
        model = FAQ

    thing = factory.SubFactory(ThingFactory)
    questioner = factory.SubFactory(UserFactory)
    question = factory.Sequence(lambda n: f"Question {n}?")


class WishResponseFactory(DjangoModelFactory):
    """A KNOW_WHERE answer to a wish by default (carries the required message)."""

    class Meta:
        model = WishResponse

    wish = factory.SubFactory(ThingFactory, type=Thing.Type.WISH_THING)
    responder = factory.SubFactory(UserFactory)
    kind = WishResponse.Kind.KNOW_WHERE
    message = factory.Sequence(lambda n: f"I know where to find item {n}")


class ThingTransferFactory(DjangoModelFactory):
    class Meta:
        model = ThingTransfer

    thing = factory.SubFactory(ThingFactory)
    from_user = factory.SubFactory(UserFactory)
    to_user = factory.SubFactory(UserFactory)
    lent_date = factory.LazyFunction(date.today)
